-- MySQL Script generated by MySQL Workbench
-- Thu Nov  6 16:30:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eqfmxn_help_desk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eqfmxn_help_desk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eqfmxn_help_desk` DEFAULT CHARACTER SET utf8 ;
USE `eqfmxn_help_desk` ;

-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`branches` (
  `id_branches` INT NOT NULL AUTO_INCREMENT,
  `branche` VARCHAR(45) NOT NULL,
  `code` VARCHAR(15) NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_branches`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`ticket_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`ticket_types` (
  `id_ticket_types` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `id_branches` INT NOT NULL,
  PRIMARY KEY (`id_ticket_types`),
  INDEX `fk_ticket_types_branches1_idx` (`id_branches` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_types_branches1`
    FOREIGN KEY (`id_branches`)
    REFERENCES `eqfmxn_help_desk`.`branches` (`id_branches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`positions` (
  `id_positions` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_positions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`users_support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`users_support` (
  `id_users_support` INT NOT NULL AUTO_INCREMENT,
  `workers_sap` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `must_change_password` tinyint(1) NOT NULL DEFAULT 1, -- Linea agregada
  `register` timestamp NOT NULL DEFAULT current_timestamp(), -- Linea agregada
  `phone` INT NULL,
  `status` TINYINT NOT NULL,
  `id_positions` INT NOT NULL,
  `id_roles` INT NOT NULL,
  `id_branches` INT NOT NULL,
  PRIMARY KEY (`id_users_support`),
  INDEX `fk_users_support_positions1_idx` (`id_positions` ASC) VISIBLE,
  INDEX `fk_users_support_roles1_idx` (`id_roles` ASC) VISIBLE,
  INDEX `fk_users_support_branches1_idx` (`id_branches` ASC) VISIBLE,
  CONSTRAINT `fk_users_support_positions1`
    FOREIGN KEY (`id_positions`)
    REFERENCES `eqfmxn_help_desk`.`positions` (`id_positions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_support_roles1`
    FOREIGN KEY (`id_roles`)
    REFERENCES `eqfmxn_help_desk`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_support_branches1`
    FOREIGN KEY (`id_branches`)
    REFERENCES `eqfmxn_help_desk`.`branches` (`id_branches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`tickets` (
  `id_tickets` INT NOT NULL AUTO_INCREMENT,
  `no_ticket` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `workers_sapU` INT NOT NULL,
  `nameU` VARCHAR(45) NOT NULL,
  `lastnameU` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `id_ticket_types` INT NOT NULL,
  `id_positions` INT NOT NULL,
  `id_users_support` INT NOT NULL,
  PRIMARY KEY (`id_tickets`),
  INDEX `fk_tickets_ticket_type_idx` (`id_ticket_types` ASC) VISIBLE,
  INDEX `fk_tickets_positions1_idx` (`id_positions` ASC) VISIBLE,
  INDEX `fk_tickets_users_support1_idx` (`id_users_support` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_ticket_type`
    FOREIGN KEY (`id_ticket_types`)
    REFERENCES `eqfmxn_help_desk`.`ticket_types` (`id_ticket_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_positions1`
    FOREIGN KEY (`id_positions`)
    REFERENCES `eqfmxn_help_desk`.`positions` (`id_positions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_users_support1`
    FOREIGN KEY (`id_users_support`)
    REFERENCES `eqfmxn_help_desk`.`users_support` (`id_users_support`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`ticket_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`ticket_images` (
  `id_ticket_images` INT NOT NULL AUTO_INCREMENT,
  `id_tickets` INT NOT NULL,
  `image_path` VARCHAR(45) NOT NULL,
  `upload_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_ticket_images`),
  INDEX `fk_ticket_images_tickets1_idx` (`id_tickets` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_images_tickets1`
    FOREIGN KEY (`id_tickets`)
    REFERENCES `eqfmxn_help_desk`.`tickets` (`id_tickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`ticket_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`ticket_status` (
  `id_ticket_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ticket_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`ticket_status_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`ticket_status_history` (
  `id_ticket_status_history` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `id_tickets` INT NOT NULL,
  `id_ticket_status` INT NOT NULL,
  PRIMARY KEY (`id_ticket_status_history`),
  INDEX `fk_ticket_status_history_tickets1_idx` (`id_tickets` ASC) VISIBLE,
  INDEX `fk_ticket_status_history_ticket_status1_idx` (`id_ticket_status` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_status_history_tickets1`
    FOREIGN KEY (`id_tickets`)
    REFERENCES `eqfmxn_help_desk`.`tickets` (`id_tickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_status_history_ticket_status1`
    FOREIGN KEY (`id_ticket_status`)
    REFERENCES `eqfmxn_help_desk`.`ticket_status` (`id_ticket_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`ticket_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`ticket_comments` (
  `id_ticket_comments` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(1000) NOT NULL,
  `date` DATETIME NOT NULL,
  `id_tickets` INT NOT NULL,
  `id_users_support` INT NOT NULL,
  PRIMARY KEY (`id_ticket_comments`),
  INDEX `fk_ticket_comments_tickets1_idx` (`id_tickets` ASC) VISIBLE,
  INDEX `fk_ticket_comments_users_support1_idx` (`id_users_support` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_comments_tickets1`
    FOREIGN KEY (`id_tickets`)
    REFERENCES `eqfmxn_help_desk`.`tickets` (`id_tickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_comments_users_support1`
    FOREIGN KEY (`id_users_support`)
    REFERENCES `eqfmxn_help_desk`.`users_support` (`id_users_support`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`ticket_user_support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`ticket_user_support` (
  `id_ticket_user_support` INT NOT NULL AUTO_INCREMENT,
  `id_tickets` INT NOT NULL,
  `id_users_support` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_ticket_user_support`),
  INDEX `fk_ticket_user_support_tickets1_idx` (`id_tickets` ASC) VISIBLE,
  INDEX `fk_ticket_user_support_users_support1_idx` (`id_users_support` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_user_support_tickets1`
    FOREIGN KEY (`id_tickets`)
    REFERENCES `eqfmxn_help_desk`.`tickets` (`id_tickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user_support_users_support1`
    FOREIGN KEY (`id_users_support`)
    REFERENCES `eqfmxn_help_desk`.`users_support` (`id_users_support`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`questions` (
  `id_questions` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NOT NULL,
  `id_branches` INT NOT NULL,
  PRIMARY KEY (`id_questions`),
  INDEX `fk_questions_branches1_idx` (`id_branches` ASC) VISIBLE,
  CONSTRAINT `fk_questions_branches1`
    FOREIGN KEY (`id_branches`)
    REFERENCES `eqfmxn_help_desk`.`branches` (`id_branches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eqfmxn_help_desk`.`ticket_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eqfmxn_help_desk`.`ticket_answers` (
  `id_ticket_answers` INT NOT NULL AUTO_INCREMENT,
  `id_ticket_user_support` INT NOT NULL,
  `id_questions` INT NOT NULL,
  `answer` INT NOT NULL,
  `ticket_answerscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ticket_answers`),
  INDEX `fk_ticket_answers_ticket_user_support1_idx` (`id_ticket_user_support` ASC) VISIBLE,
  INDEX `fk_ticket_answers_questions1_idx` (`id_questions` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_answers_ticket_user_support1`
    FOREIGN KEY (`id_ticket_user_support`)
    REFERENCES `eqfmxn_help_desk`.`ticket_user_support` (`id_ticket_user_support`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_answers_questions1`
    FOREIGN KEY (`id_questions`)
    REFERENCES `eqfmxn_help_desk`.`questions` (`id_questions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;